### ISSUE TITLE
SSLError after installation

### ISSUE THREAD

**Issue by Fadope1** [croian/mouseless-issues#24]
### mouseless version

0.2.0

### macOS version

Sequoia 15.1

### What happened?

After installation I try activating the trial, then window appeared with the following text:

```
Unexpected error. SSLError: HTTPSConnectionPool(host='[host]', port=443): Max retries exceeded with url: [trial] (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
```

Maybe add flag called verify_ssl so it can be set to false.

### Steps to Reproduce

1. Install
2. Start Trial

**Comment by croian** [comment]
hi @Fadope1, please see the troubleshooting section in the [docs](https://github.com/croian/mouseless-issues/blob/main/mouseless_documentation.md) for the current workaround for this.  i realized it's probably not good to have urls in these error messages, which should be fixed in the upcoming patch release.  I'm going for extra security through obscurity,  so I'm going to delete this issue in a few minutes.

thank you for the report though!  i hope the workaround works for you for now.

**Comment by croian** [comment]
also @Fadope1 please reach out to me directly, e.g. through the https://mouseless.click/support email if you want further assistance.

**Comment by croian** [comment]
hi @Fadope1 thank you for the report!  please see the [docs](https://github.com/croian/mouseless-issues/blob/main/mouseless_documentation.md) for the current workaround, and please let me know if it doesn't work or isn't suitable for you.

**Comment by Fadope1** [comment]
Yes this resolved it, thanks for the quick help!

**Comment by ryanseddon** [comment]
Just to update on this on my machine I had to run the bash script inside the app and enable accessibility controls for my terminal for this env variable to work. Not sure if this is my corp machine doing something weird but the app would never start.

Would be good to have a solution to this that doesn't require any of this to get it working.

**Comment by croian** [comment]
Thank you for the feedback, @ryanseddon. I actually just fixed this a couple days ago.  Starting with the next preview release (some time in next 2-4 days), you'll be able to import the cert via an in-app dialog -- no need to run from terminal.
